theme: jekyll-theme-minimal
title: Sujin Han
# logo: "/images/sujin_han.jpg"
description: >
  <img src="/images/sujin_han.jpg" alt="Sujin Han" style="width:70%;height:auto;">
  <br>
  <b>Email:</b> sujinhan@kaist.ac.kr
  <br>
  <b>Research Interests:</b><br>
  - Mobile Systems<br>
  - Software Security<br>
  
theme: jekyll-theme-minimal